version: '3.8' 
services: 
  app: 
    build: . 
    ports: 
      - "8000:8000" 
    environment: 
      - DATABASE_URL=postgresql://user:pass@db:5432/smart_registry 
      - REDIS_URL=redis://redis:6379 
    depends_on: 
      - db 
      - redis 
  db: 
    image: postgres:15 
    environment: 
      POSTGRES_DB: smart_registry 
      POSTGRES_USER: user 
      POSTGRES_PASSWORD: pass 
  redis: 
    image: redis:7-alpine 
